(function(){
'use strict';
var API='https://wongming-ai.vercel.app';
var LANG={'zh-Hant':'繁體中文','zh-Hans':'简体中文','en':'English','ja':'日本語','ko':'한국어'};
var VOICE={'zh-Hant':'zh-TW-HsiaoChenNeural','zh-Hans':'zh-CN-XiaoxiaoNeural','en':'en-US-AriaNeural','ja':'ja-JP-NanamiNeural','ko':'ko-KR-SunHiNeural'};
var UI={
'zh-Hant':{label:'💬 你可以問我：',question:'我有疑問',tour:'能帶我瀏覽帝國嗎',voice:'語音聽不見',mic:'麥克風怎麼用？',what:'我可以說什麼？',translate:'🌐 選擇頁面語言：'},
'zh-Hans':{label:'💬 你可以问我：',question:'我有疑问',tour:'能带我浏览帝国吗',voice:'听不见语音',mic:'麦克风怎么用？',what:'我可以说什么？',translate:'🌐 选择页面语言：'},
'en':{label:'💬 You can ask me:',question:'I have a question',tour:'Can you show me around the Empire?',voice:'I cannot hear the voice',mic:'How do I use the microphone?',what:'What can I say?',translate:'🌐 Choose page language:'},
'ja':{label:'💬 こんなことを聞けます：',question:'質問があります',tour:'帝国を案内してくれますか？',voice:'音声が聞こえません',mic:'マイクはどう使いますか？',what:'何を聞けますか？',translate:'🌐 ページの言語を選択：'},
'ko':{label:'💬 이렇게 물어보세요:',question:'질문이 있어요',tour:'제국을 안내해 줄 수 있나요?',voice:'음성이 들리지 않아요',mic:'마이크는 어떻게 사용하나요?',what:'무엇을 물어볼 수 있나요?',translate:'🌐 페이지 언어 선택:'}
};
var PARENT_ORIGIN='*';try{PARENT_ORIGIN=new URL(document.referrer).origin||'*';}catch(e){}
var state={language:'zh-Hant',country:'',ready:false};var cache=new Map();
function mapCountry(country){country=String(country||'').toUpperCase();if(country==='TW'||country==='HK'||country==='MO')return'zh-Hant';if(country==='CN'||country==='SG')return'zh-Hans';if(country==='JP')return'ja';if(country==='KR')return'ko';if(country)return'en';return'';}
async function detect(){try{var r=await fetch(API+'/api/locale',{cache:'no-store'});if(r.ok){var j=await r.json();if(LANG[j.language]){state.language=j.language;state.country=j.country||'';return;}}}catch(e){}try{var r2=await fetch('https://ipapi.co/json/',{cache:'no-store'});if(r2.ok){var j2=await r2.json();var byCountry=mapCountry(j2.country_code||j2.country);if(byCountry){state.language=byCountry;state.country=j2.country_code||j2.country||'';return;}}}catch(e){}var l=(navigator.language||'').toLowerCase();state.language=l.indexOf('zh-tw')===0||l.indexOf('zh-hk')===0||l.indexOf('zh-mo')===0||l.indexOf('zh-hant')===0?'zh-Hant':l.indexOf('zh')===0?'zh-Hans':l.indexOf('ja')===0?'ja':l.indexOf('ko')===0?'ko':'en';}
async function translate(text){if(!text)return text;await state.promise;if(state.language==='zh-Hant')return text;var key=state.language+'|'+text;if(cache.has(key))return cache.get(key);try{var r=await fetch(API+'/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:state.language,items:[String(text).slice(0,900)]})});if(!r.ok)return text;var j=await r.json();var out=j.translations&&j.translations[0]?String(j.translations[0]):text;cache.set(key,out);return out;}catch(e){return text;}}
function localizeSuggestions(){var box=document.getElementById('suggestions');if(!box)return;var ui=UI[state.language]||UI['zh-Hant'];var label=box.querySelector('.sg-label');if(label)label.textContent=ui.label;var buttons=box.querySelectorAll('.sugg');var values=[ui.question,ui.tour,ui.voice,ui.mic,ui.what];for(var i=0;i<values.length&&i<buttons.length;i++)buttons[i].textContent=values[i];}
state.promise=detect();
window.WM_I18N={getLanguage:function(){return state.language;},getVoice:function(){return VOICE[state.language]||VOICE['zh-Hant'];},getUI:function(){return UI[state.language]||UI['zh-Hant'];},ready:function(){return state.promise;},localize:translate,setLanguage:function(lang){if(LANG[lang]){state.language=lang;state.ready=true;localizeSuggestions();}},openMenu:function(){var box=document.getElementById('suggestions');if(!box)return;box.innerHTML='';var title=document.createElement('div');title.className='sg-label';title.textContent=(UI[state.language]||UI['zh-Hant']).translate;box.appendChild(title);[['English','en'],['日本語','ja'],['한국어','ko'],['简体中文','zh-Hans'],['繁體中文','zh-Hant']].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='sugg';b.textContent=x[0];b.onclick=function(){window.WM_I18N.setLanguage(x[1]);try{window.parent.postMessage({ns:'avatar-widget',type:'action',action:{action:'translate',target:x[1]}},PARENT_ORIGIN);}catch(e){}box.innerHTML='';if(typeof window.showBubble==='function')window.showBubble('Language: '+x[0]);};box.appendChild(b);});}};
state.promise.then(function(){state.ready=true;var b=document.getElementById('btn-llm');if(b){b.textContent='🌐';b.setAttribute('aria-label',(UI[state.language]||UI['zh-Hant']).translate);b.title=(UI[state.language]||UI['zh-Hant']).translate+'｜導覽語言：'+LANG[state.language];b.onclick=window.WM_I18N.openMenu;}localizeSuggestions();try{window.parent.postMessage({ns:'avatar-widget',type:'visitor-locale',language:state.language,country:state.country},PARENT_ORIGIN);}catch(e){}});
})();